---
- include: generate-key.yml

- name: Update github with the deploy key
  uri:
    url: "{{ github_api_deploy_key_add_url }}"
    headers:
      Authorization: "token {{ github_deploy_api_token | mandatory }}"
    method:         POST
    body_format:    json
    status_code:    201
    return_content: yes
    body:
      title:        "{{ github_deploy_public_key_title }}"
      key:          "{{ github_deploy_ssh_public_key }}"
      read_only:    "{{ 'false' if not github_deploy_read_only else 'true' }}"
  register:     github_api_deploy_key_add_response
  no_log:       yes
  delegate_to:  "{{ github_deploy_local_delegate }}"

- name: Set a fact for the Key ID
  set_fact:
    github_api_deploy_key_id: "{{ github_api_deploy_key_add_response.json.id }}"

- include: keyscan.yml
  when:    github_deploy_keyscan_enable

- include: create-host-key.yml
  when:     github_deploy_create_host_key
...
